// app1/vue/csr/my-vue-project/src/components/BackgroundAnimation.vue
<template>
  <canvas ref="canvas" class="background">Canvas not supported.</canvas>
</template>

<script>
export default {
  name: "BackgroundAnimation",
  mounted() {
    const canvas = this.$refs.canvas;
    if (!canvas || !canvas.getContext) return;

    const ctx = canvas.getContext("2d");
    let X = (canvas.width = window.innerWidth);
    let Y = (canvas.height = window.innerHeight);
    const shapeNum = 300;
    const shapes = [];

    const rand = (min, max) => Math.floor(Math.random() * (max - min + 1) + min);

    class Shape {
      constructor(ctx, x, y) {
        this.ctx = ctx;
        this.init(x, y);
      }

      init(x, y) {
        this.x = x;
        this.y = y;
        this.r = rand(10, 25);
        this.ga = Math.random() * Math.random() * Math.random() * Math.random();
        this.v = {
          x: Math.random(),
          y: -1,
        };
        this.l = rand(0, 20);
        this.sl = this.l;
      }

      updateParams() {
        const ratio = this.l / this.sl;
        this.l -= 1;
        if (this.l < 0) {
          this.init(X * (Math.random() + Math.random()) / 2, rand(0, Y));
        }
      }

      updatePosition() {
        this.x += Math.random();
        this.y += -Math.random();
      }

      draw() {
        const ctx = this.ctx;
        ctx.save();
        ctx.globalCompositeOperation = "lighter";
        ctx.globalAlpha = this.ga;
        ctx.fillStyle = "white";
        ctx.beginPath();
        ctx.arc(this.x, this.y, this.r, 0, Math.PI * 2, false);
        ctx.fill();
        ctx.restore();
      }

      render() {
        this.updatePosition();
        this.updateParams();
        this.draw();
      }
    }

    for (let i = 0; i < shapeNum; i++) {
      shapes.push(new Shape(ctx, X * (Math.random() + Math.random()) / 2, rand(0, Y)));
    }

    const render = () => {
      ctx.clearRect(0, 0, X, Y);
      shapes.forEach((shape) => shape.render());
      requestAnimationFrame(render);
    };

    const onResize = () => {
      X = canvas.width = window.innerWidth;
      Y = canvas.height = window.innerHeight;
    };

    window.addEventListener("resize", onResize);

    render();

    this.cleanup = () => {
      window.removeEventListener("resize", onResize);
    };
  },
  beforeUnmount() {
    if (this.cleanup) this.cleanup();
  },
};
</script>

// app1/angular/ssr/angular-ssr/src/app/background-animation/background-animation.component.ts
import { Component, ElementRef, HostListener, Inject, OnDestroy, OnInit, PLATFORM_ID, ViewChild } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';

@Component({
  selector: 'app-background-animation',
  templateUrl: './background-animation.component.html',
  styleUrls: ['./background-animation.component.css'],
})
export class BackgroundAnimationComponent implements OnInit, OnDestroy {
  @ViewChild('canvas', { static: true }) canvasRef!: ElementRef<HTMLCanvasElement>;
  private ctx!: CanvasRenderingContext2D | null;
  private shapes: Shape[] = [];
  private animationFrameId!: number;
  private X!: number;
  private Y!: number;
  private shapeNum: number = 300;
  private isBrowser: boolean;

  constructor(@Inject(PLATFORM_ID) private platformId: Object) {
    this.isBrowser = isPlatformBrowser(this.platformId);
  }

  ngOnInit(): void {
    if (!this.isBrowser) return; // Skip initialization if not running in the browser

    const canvas = this.canvasRef.nativeElement;
    this.ctx = canvas.getContext('2d');
    this.resizeCanvas();

    for (let i = 0; i < this.shapeNum; i++) {
      this.shapes.push(
        new Shape(this.ctx!, this.X * (Math.random() + Math.random()) / 2, this.rand(0, this.Y))
      );
    }

    this.render();
  }

  @HostListener('window:resize')
  onResize(): void {
    if (!this.isBrowser) return;
    this.resizeCanvas();
  }

  private resizeCanvas(): void {
    const canvas = this.canvasRef.nativeElement;
    this.X = canvas.width = window.innerWidth;
    this.Y = canvas.height = window.innerHeight;
  }

  private render = (): void => {
    if (!this.ctx) return;

    this.ctx.clearRect(0, 0, this.X, this.Y);
    this.shapes.forEach((shape) => shape.render());
    this.animationFrameId = requestAnimationFrame(this.render);
  };

  private rand(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  ngOnDestroy(): void {
    if (this.isBrowser) {
      cancelAnimationFrame(this.animationFrameId);
    }
  }
}

class Shape {
  private x!: number;
  private y!: number;
  private r!: number;
  private ga!: number;
  private v!: { x: number; y: number };
  private l!: number;
  private sl!: number;

  constructor(private ctx: CanvasRenderingContext2D, x: number, y: number) {
    this.init(x, y);
  }

  private rand(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  private init(x: number, y: number): void {
    this.x = x;
    this.y = y;
    this.r = this.rand(10, 25);
    this.ga = Math.random() ** 4;
    this.v = { x: Math.random(), y: -1 };
    this.l = this.rand(0, 20);
    this.sl = this.l;
  }

  private updateParams(): void {
    this.l -= 1;
    if (this.l < 0) {
      this.init(window.innerWidth * (Math.random() + Math.random()) / 2, this.rand(0, window.innerHeight));
    }
  }

  private updatePosition(): void {
    this.x += Math.random();
    this.y -= Math.random();
  }

  private draw(): void {
    const ctx = this.ctx;
    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    ctx.globalAlpha = this.ga;
    ctx.fillStyle = 'white';
    ctx.beginPath();
    ctx.arc(this.x, this.y, this.r, 0, Math.PI * 2, false);
    ctx.fill();
    ctx.restore();
  }

  render(): void {
    this.updatePosition();
    this.updateParams();
    this.draw();
  }
}
